### ISSUE TITLE
Server's config not being hidden after restart

### ISSUE THREAD

**Issue by ndv400** [Ex-Presidents/CopiedLobbyMess#2]
After rebooting the server:
![image](https://user-images.githubusercontent.com/1404955/34452748-77eafe98-ed57-11e7-85ff-f54062bcfb54.png)
After doing /rocket reload:
![image](https://user-images.githubusercontent.com/1404955/34452749-80736eec-ed57-11e7-8c13-24facd1499fa.png)

So, in order to hide my server's config I have to do /rocket reload after every time I restart it. Any way to fix this?

**Comment by AtiLion** [comment]
I will check it out

**Comment by ndv400** [comment]
Any progress? @AtiLion

**Comment by AtiLion** [comment]
@Daniil1288 Haven't had a chance to check it out yet. Really busy with school and work

**Comment by DronXa** [comment]
Still doesn't work :P

**Comment by ndv400** [comment]
Very true. I'm doing /rocket reload's to this day, oh well :P

**Comment by ExtraJuiceMan** [comment]
lol this shit is going to break anyway with the new update when nolson changes all of the tags

maybe ill update it for you guys then

**Comment by ndv400** [comment]
@ExtraConcentratedJuice dw I did it myself and no one else's using it lol 
also fixed the rocket reload thing
I don't know how to use github properly so I'm not going to make a PR

**Comment by ExtraJuiceMan** [comment]
I forgot about it lol

I'll update it in a bit because I am a kind soul

**Comment by ExtraJuiceMan** [comment]
https://github.com/Ex-Presidents/CopiedLobbyMess/releases/tag/1.1.0
