### ISSUE TITLE
Not disabling workshop when HideWorkshop is set to true

### ISSUE THREAD

**Issue by oshanshan** [Ex-Presidents/CopiedLobbyMess#3]
My server still is appearing as workshop with hideworkshop enabled. Anybody have a fix?

**Comment by AtiLion** [comment]
Do you by any chance have MessWorkshop enabled?

**Comment by AtiLion** [comment]
I have found and fixed the issue, the new release is down below.
If the problem still occurs please make sure that the "MessConfig" option is enabled and the "MessWorkshop" option is disabled.

New release: https://github.com/Ex-Presidents/CopiedLobbyMess/releases/tag/1.2.1

**Comment by oshanshan** [comment]
Seems to have fixed the issue. Thank you
