### ISSUE TITLE
Update copiedlobbymess

### ISSUE THREAD

**Issue by DonRuggero** [Ex-Presidents/CopiedLobbyMess#4]
Can someone update copiedlobbymess? The latest release don't work

**Comment by oshanshan** [comment]
It works perfectly for me. What is your issue?

**Comment by Eiromplays** [comment]
I just cant manage to get this on my server I have tried. I hope someone can help me. Becase I Think this plugin is rly cool. I know this is for Updated issue but Didnt find any other place to post this so just posted it here.

**Comment by Stitch626** [comment]
It worked for me just perfectly fine. Thanks to the creator for fighting against the DMCA-takedown :)

**Comment by Kr4ken-9** [comment]
I am closing this issue because saying it doesn't work is not descriptive and won't help anyone fix it. If you comment with details I will reopen this issue and look into fixing it.
